import json

def q(question, answers, correct):
    return {"q": question, "a": answers, "c": correct}

def ch(id,icon,title,sub,color,intro,body,steps,quiz):
    if len(steps)<10: steps = steps + ["I understand this"]*(10-len(steps))
    return {"id":id,"icon":icon,"title":title,"subtitle":sub,"color":color,"accent":color+"22",
        "intro":intro,"body":body,"steps":steps[:10],
        "tip":"Master this skill!","trigger":"Focus on this at your next session!",
        "deepWhy":["WHY is this important in a real match?","HOW do the best players use this?"],
        "deepScenario":"Describe a match situation where this would be crucial.",
        "quiz":quiz}

CH = []

# ===== 1. PITCH =====
CH.append(ch("pitch","⚽","The Pitch","Lines, Areas & Markings","#16a34a",
"Every line on a football pitch means something. Understanding the pitch is the first step to understanding the game.",
["<b>KEY MARKINGS:</b>","Touchlines (long sides) and goal lines (short sides) — ball must FULLY cross to be out","Halfway line — kick-offs here, can't be offside in your own half","Penalty area — GK uses hands here, fouls here = penalty","6-yard box — goal kicks taken from here","Penalty spot — 12 yards from goal","Centre circle — opponents stay out at kick-off (9.15m radius)","The D/arc — players stay outside during penalties","Corner arcs — corners taken from here, flag can't be moved"],
["Touchlines and goal lines","Penalty area rules","6-yard box for goal kicks","Penalty spot = 12 yards","Centre circle at kick-offs","The D at penalty time","Corner arcs","Can't be offside in own half","GK hands only in penalty area","I know all pitch markings"],
[q("Penalty area = GK can?",["Kick only","Use HANDS here","Do anything","Nothing special"],1),q("6-yard box is for?",["Penalties","GOAL KICKS","Corners","Throw-ins"],1),q("Penalty spot distance?",["6 yards","10 yards","12 YARDS","18 yards"],2),q("Can't be offside in?",["Their half","YOUR OWN HALF","Penalty area","Centre circle"],1),q("At kick-off opponents outside?",["Penalty area","CENTRE CIRCLE","6-yard box","Their own half"],1),q("Ball must cross line how much?",["Halfway","FULLY — completely over","Just touch","Doesn't matter"],1),q("The D is used during?",["Corners","PENALTIES — keep players back","Goal kicks","Throw-ins"],1),q("Corners taken from?",["6-yard box","CORNER ARC","Centre spot","Penalty spot"],1),q("Touchlines are the?",["Short sides","LONG sides","Goal lines","Centre line"],1),q("Goal lines are the?",["Long sides","SHORT sides (where goals are)","Halfway","Touchlines"],1)]))

# ===== 2. RULES =====
CH.append(ch("rules","📏","The Rules","Offside, Fouls & Restarts","#1d4ed8",
"Football has 17 Laws of the Game. Understanding the key rules makes you a smarter player. The offside rule alone wins and loses matches.",
["<b>OFFSIDE:</b> You're offside if closer to goal than BOTH the ball AND second-last defender when ball is PLAYED (not received). NOT offside from throw-in, goal kick, or corner. NOT offside in your own half. Level = onside.","","<b>FOULS:</b> Kicking, tripping, pushing, holding, handball = free kick. In the box = penalty!","","<b>DIRECT FK:</b> Can score directly. For contact fouls/handball.","<b>INDIRECT FK:</b> Someone else must touch first. For obstruction/dangerous play.","","<b>THROW-INS:</b> Both feet on/behind line, both hands, behind head. Can't score directly. Can't be offside.","","<b>GOAL KICK:</b> From 6-yard box. Can't be offside. <b>CORNER:</b> From corner arc. CAN score directly (Olimpico!). Can't be offside."],
["Offside: behind ball AND second-last defender when PLAYED","Not offside: own half, throw-in, goal kick, corner","Level with defender = onside","Direct FK: can score directly","Indirect FK: someone else touches first","Throw-in: both feet, both hands, behind head","Goal kick from 6-yard box","Can score directly from corner","Fouls in box = penalty","Handball by outfield player = free kick"],
[q("Offside judged when ball is?",["Received","PLAYED/passed","Controlled","Shot"],1),q("Not offside from?",["Free kick","THROW-IN, GOAL KICK, CORNER","Normal pass","Cross"],1),q("Level with defender?",["Offside","ONSIDE!","Foul","Penalty"],1),q("Direct FK means?",["Must pass first","CAN score directly","Two touches","Indirect"],1),q("Throw-in: feet must be?",["In the air","BOTH on/behind the line","One foot only","Anywhere"],1),q("Foul in the box =?",["Free kick","PENALTY!","Corner","Goal kick"],1),q("Can you score from a corner?",["No","YES — Olimpico!","Only with head","Never"],1),q("Goal kicks from?",["Penalty spot","SIX-YARD BOX","Centre","Corner"],1),q("In your own half, offside?",["Yes","NO — can't be offside in own half","Sometimes","Only if behind ball"],1),q("Handball by outfield player?",["Play on","FREE KICK to other team","Penalty always","Corner"],1)]))

# ===== 3. CARDS =====
CH.append(ch("cards","🟨","Cards & Fouls","Stay on the Pitch","#f59e0b",
"Yellow = warning. Two yellows = red = off. Straight red = serious. Know what gets you carded and play smart.",
["<b>YELLOW:</b> Unsporting behaviour, dissent, time-wasting, persistent fouling, delaying restart","<b>RED:</b> Serious foul play, violent conduct, denying obvious goal, offensive language, second yellow","Professional foul (stopping breakaway) in box = penalty + possible red","Tactical fouls (shirt pull to stop counter) = usually yellow","VAR checks: goals, penalties, reds, mistaken identity"],
["Yellow = warning","Two yellows = red = off","Straight red for serious/violent","Professional foul = red + penalty possible","Tactical fouls risk a yellow","VAR checks goals, pens, reds","Dissent = yellow","Persistent fouling = yellow","I play fair","I know what gets cards"],
[q("Two yellows =?",["Warning","RED — sent off!","Free kick","Nothing"],1),q("Denying obvious goal =?",["Yellow","RED card","Play on","Corner"],1),q("Pulling shirt to stop counter?",["Play on","Usually YELLOW","Red","Nothing"],1),q("Professional foul in box?",["Free kick","PENALTY + possible RED","Yellow only","Corner"],1),q("VAR checks?",["Everything","Goals, penalties, reds, identity","Throw-ins","Corners"],1),q("Arguing with ref?",["Fine","YELLOW for dissent","Red","Nothing"],1),q("Violent conduct?",["Yellow","RED card","Warning","Free kick"],1),q("Persistent fouling?",["Nothing","YELLOW card","Red","Play on"],1),q("Second yellow same as?",["Warning","RED — you're off!","Nothing","Free kick"],1),q("Serious foul play?",["Yellow","RED — dangerous tackle","Free kick only","Corner"],1)]))

# ===== 4. STRUCTURE =====
CH.append(ch("structure","⏱️","Match Structure","Halves, Extra Time & Pens","#7c3aed",
"A match is 90 minutes but there's a lot more to know about how a game is structured.",
["2 × 45 mins, 15-minute half-time","Injury time added each half (1-5+ mins)","Extra time (knockouts): 2 × 15 mins","Penalties: 5 each then sudden death","3 subs (or 5 in many competitions now)","Subbed off = can't return","Subs enter at halfway line","Keeper: one foot on line for penalties","No golden goal — play full extra time"],
["90 mins total","15-min half-time","Injury time added","Extra time 2x15","Pens: 5 each then sudden death","Can't return after subbed off","Subs at halfway line","Keeper foot on line for pens","No golden goal anymore","I understand match structure"],
[q("Match length?",["60 mins","2x45 = 90 MINUTES","120 mins","2x30"],1),q("Half-time?",["5 mins","15 MINUTES","20 mins","10 mins"],1),q("Extra time?",["2x10","2x15 MINUTES","1x30","2x20"],1),q("Penalties each?",["3","5","7","10"],1),q("Subbed off, return?",["Yes","NO","Only in ET","If injured"],1),q("Injury time for?",["Fun","Time lost to injuries, subs, VAR","Practice","Water"],1),q("Subs enter at?",["Goal line","HALFWAY LINE","Corner","Anywhere"],1),q("Keeper at pen?",["Both feet on line","ONE FOOT on line","Anywhere","Off the line"],1),q("After 5 pens each, tied?",["Replay","SUDDEN DEATH","Coin toss","Draw"],1),q("Golden goal used?",["Yes","NO — play full extra time","Sometimes","World Cup only"],1)]))

# ===== 5. POSITIONS =====
CH.append(ch("positions","🧤","Positions","Every Role Explained","#dc2626",
"Every position has a specific job. Understanding ALL positions makes you better no matter where you play.",
["<b>GK (1):</b> Last line, commands box, organises defence, distributes","<b>CB (4,5):</b> Win headers, tackle, read game, organise","<b>RB/LB (2,3):</b> Defend wings AND overlap to attack. Need pace + stamina","<b>CDM (6):</b> Protects back four, breaks up play, simple passes","<b>CM (8):</b> Box-to-box engine, tackles AND creates","<b>CAM (10):</b> Playmaker, vision, final pass, between the lines","<b>Wingers (7,11):</b> Pace, dribble, cross, cut inside to shoot","<b>ST (9):</b> Goalscorer, movement, finishing, composure"],
["GK = last line, hands in box","CB = headers, tackles, organise","Full-backs = defend AND attack","CDM = protect back four","CM = box-to-box engine","CAM = playmaker, vision","Wingers = pace, cross, cut inside","Striker = goals and movement","Every position attacks AND defends","I know all positions"],
[q("Who can use hands?",["Anyone","Only GK in THEIR box","Nobody","Centre-back"],1),q("The '6' is?",["Striker","HOLDING midfielder","GK","Winger"],1),q("Full-backs need to?",["Only defend","DEFEND AND ATTACK wide","Only attack","Stay central"],1),q("The '10' is?",["GK","CB","PLAYMAKER/CAM","Striker"],2),q("Box-to-box mid does?",["Only defends","EVERYTHING — tackles AND creates","Only attacks","Passes sideways"],1),q("Striker needs?",["Only pace","COMPOSURE, movement, finishing","Only strength","Heading only"],1),q("Wingers need?",["Strength only","PACE, dribbling, and delivery","Just heading","Only passing"],1),q("CB must?",["Score goals","WIN HEADERS, tackle, organise","Dribble past everyone","Take corners"],1),q("#9 is typically?",["GK","Left-back","STRIKER","Midfielder"],2),q("Modern football demands?",["One job only","Attack AND defend in every position","Never move","Stay still"],1)]))

# ===== 6-36: All remaining chapters =====
bulk = [
("first-touch","🦶","First Touch","Control is Everything","#6d28d9","Your first touch decides everything. 1-2 seconds before a defender arrives. Good touch = time. Bad touch = trouble.",
["Cushion: let foot 'give', don't kick at it","Inside foot = most control","Body OPEN before ball arrives — see ball AND pitch","Touch INTO SPACE not under feet","Chest: puff out then sink as ball arrives","Thigh: flat surface, cushion down","Sole: stop dead in tight spaces","First touch = a pass to yourself","1-2 seconds before defender closes","Practice with both feet"],
[q("Secret to control?",["Kick hard","CUSHION — let foot give","Head it","Toe poke"],1),q("Body shape?",["Square","OPEN — see ball AND pitch","Back to play","Doesn't matter"],1),q("Touch goes?",["Under feet","INTO SPACE","Backward","Up"],1),q("Best surface?",["Toe","Laces","INSIDE OF FOOT","Heel"],2),q("Chest control?",["Jump away","Puff then SINK as ball hits","Catch it","Head it"],1),q("First touch is like?",["A shot","A PASS TO YOURSELF","A tackle","A header"],1),q("Square-on means only?",["Forward","BACK — no forward options","Sideways","Through ball"],1),q("Time before defender?",["10 secs","1-2 SECONDS","30 secs","All day"],1),q("Thigh uses?",["Knee","FLAT surface, cushion down","Shin","Back of leg"],1),q("Sole is for?",["Long pass","STOPPING DEAD in tight spaces","Shooting","Crossing"],1)]),

("passing","⚡","Passing","Weight & Accuracy","#0ea5e9","The best teams pass best. Weight (how hard) matters as much as direction.",
["Inside foot = safest, most accurate","Weight: not too hard, not too soft — invites control","Standing still = pass to feet. Running = pass into SPACE","Through ball = between/behind defenders","Long pass: lean back, laces, strike under ball","One-touch: body set BEFORE ball arrives","Disguise: look one way, pass the other","Follow through toward target","Pass into the receiver's FRONT foot","Vary: short, long, through, switch play"],
[q("Most accurate pass?",["Toe","INSIDE OF FOOT","Outside","Heel"],1),q("Pass weight means?",["Ball weight","HOW HARD — right pace for control","Player weight","Nothing"],1),q("Running teammate?",["Behind them","INTO SPACE ahead!","At feet","At defender"],1),q("Through ball goes?",["Back","BETWEEN/behind defenders","To corner","Over bar"],1),q("Long pass?",["Inside gently","LEAN BACK, laces, under ball","Toe poke","Head"],1),q("One-touch needs?",["Lots of time","Body set BEFORE ball arrives","To stop ball first","Nothing"],1),q("Disguise?",["Showing intent","Look one way, PASS OTHER","Hiding","Shouting"],1),q("Follow through?",["Stop dead","TOWARD TARGET","Fall over","Backward"],1),q("Too hard =?",["Great","Can't CONTROL it","Always good","No problem"],1),q("Pass to receiver's?",["Back foot","FRONT FOOT","Head","Shin"],1)]),

("shooting","🎯","Shooting","Placement vs Power","#dc2626","Placement beats power. Pick your spot. Hit the target. Low corners are hardest for keepers.",
["Body OVER ball = keeps it low","Side foot = accuracy","Laces = power","Non-standing foot points at target","Head down, eyes on ball at contact","Follow through toward target","Low corners hardest for keepers","Across the keeper most effective","Composure: take extra touch if needed","Practice with both feet, practice tired"],
[q("Keep shot low?",["Lean back","BODY OVER the ball","Kick toe","Close eyes"],1),q("Side foot =?",["Power","ACCURACY/placement","Spin","Heading"],1),q("Non-standing foot?",["Backward","POINTS AT TARGET","Sideways","Up"],1),q("Across keeper?",["At them","FAR CORNER — hardest to save","Over bar","Into hands"],1),q("Low corners?",["Easy","HARDEST for keepers","Pointless","Only pens"],1),q("Follow through?",["Stop","TOWARD TARGET direction","Fall over","Backward"],1),q("Composure means?",["Panic","CALM, pick spot, take time","Rush","Blast it"],1),q("Eyes at contact?",["On goal","ON THE BALL","On keeper","Closed"],1),q("Practice when?",["Fresh only","TIRED — matches decided tired","Never","Only warm-up"],1),q("Both feet?",["Strong only","YES — practice BOTH","Weak only","Neither"],1)]),

("heading","🧠","Heading","Forehead, Eyes Open","#92400e","Heading is technique not just jumping. Forehead contact, eyes open, attack the ball.",
["FOREHEAD — flat area above eyebrows","Eyes OPEN, watch ball all the way","ATTACK the ball — go to it, don't wait","Timing > jump height","Power from CORE and back, not just neck","Defensive: head UNDER ball = height + distance","Attacking: head OVER ball = aim down at goal","Practice with soft balls first","Follow FA guidelines on heading limits","Arch back, snap forward for power"],
[q("Which part?",["Top","FOREHEAD","Side","Back"],1),q("Eyes?",["Closed","OPEN — watch ball onto head","On goal","Shut"],1),q("Defensive header?",["Down","HEIGHT and distance — under the ball","At goal","Sideways"],1),q("Attacking header?",["High","DOWN toward goal — over the ball","Backward","Wide"],1),q("Power from?",["Neck only","CORE and back — snap forward","Legs","Arms"],1),q("Timing vs height?",["Height","TIMING more important","Same","Neither"],1),q("Practice with?",["Hard balls first","SOFT balls first","No practice","Tennis balls"],1),q("You should?",["Let it hit you","ATTACK the ball — go TO it","Duck","Head eyes closed"],1),q("Heading limits?",["No limits","Follow FA GUIDELINES","Never head","Adults only"],1),q("Arch back and?",["Stay back","SNAP FORWARD for power","Lean sideways","Fall over"],1)]),

("dribbling","🏃","Dribbling","Close Control","#7c3aed","Dribbling is controlled movement with purpose. Small touches, head up, change of pace.",
["Ball CLOSE — small touches","BOTH feet","Head UP — see the pitch","Change of PACE — slow then burst","Change of DIRECTION","Dribble to beat a player, pass if teammate free","Body between ball and defender","Low centre of gravity — bent knees","Touch every stride in tight spaces","Practice cones at speed"],
[q("Keep ball?",["Far","CLOSE — small touches","At arm's length","Doesn't matter"],1),q("Use?",["Strong only","BOTH feet","Weak only","Neither"],1),q("Head?",["Down at ball","UP — see the pitch","Backward","Closed eyes"],1),q("Change of pace?",["Same speed","SLOW then BURST","Always fast","Always slow"],1),q("Dribble when?",["Always","To BEAT a player — pass if free teammate","Never","Own half only"],1),q("Protect ball?",["Kick away","BODY between ball and defender","Fall over","Pass back"],1),q("Centre of gravity?",["Tall","LOW — bent knees","Jumping","Lying down"],1),q("Tight spaces?",["Big touches","EVERY STRIDE — tiny touches","Kick and run","Give up"],1),q("Practice with?",["Nothing","CONES at speed","Only matches","Walls"],1),q("Direction changes make you?",["Predictable","UNPREDICTABLE","Slower","No difference"],1)]),

("turning","🔄","Turning","Cruyff, Drag Back & Hooks","#0891b2","Turning takes you from facing your goal to facing theirs. Master these 4 turns.",
["DRAG BACK: sole on ball, pull back, turn","CRUYFF: shape to pass, chop behind standing leg, spin away","INSIDE HOOK: hook with inside, turn body","OUTSIDE HOOK: faster — outside of foot","Use when defender is tight behind","Stay low and balanced","Sell the fake first","BURST of speed AFTER the turn","Practice all 4","Turn AWAY from pressure"],
[q("Drag back uses?",["Laces","SOLE of foot","Toe","Heel"],1),q("Cruyff chops?",["Forward","BEHIND standing leg","Over head","Sideways"],1),q("After turn?",["Stop","BURST away with speed","Walk","Pass back"],1),q("Use turns when?",["Defender far","Defender TIGHT BEHIND","No one near","In goal"],1),q("Named after?",["A country","JOHAN CRUYFF","A boot","A ball"],1),q("Body shape?",["Tall stiff","LOW, balanced, quick feet","Falling","Upright"],1),q("Sell the fake?",["Actually pass","Make them BELIEVE other direction","Fall over","Shout"],1),q("Fastest turn?",["Drag back","Cruyff","Inside hook","OUTSIDE HOOK"],3),q("Turn away from?",["Space","PRESSURE","Goal","Teammates"],1),q("Practice?",["One turn","ALL 4","None","Match only"],1)]),

("weak-foot","🦵","Weak Foot","Twice the Player","#64748b","One foot = predictable. Two feet = unpredictable = dangerous. Defenders hate two-footed players.",
["10+ minutes EVERY session on weak foot","Start: wall passes","Progress: control, then shooting","Use in safe areas in matches first","Two feet = unpredictable","Defenders exploit one-footed players","Awkward at first = NORMAL","Target: everything strong foot does","Opens new passing angles","Most pros specifically trained their weak foot"],
[q("Weak foot practice?",["0 mins","10+ MINUTES every session","1 min","Only when told"],1),q("Start with?",["Shooting","WALL PASSES — simple first","Headers","Tackling"],1),q("Two-footed means?",["Looks cool","UNPREDICTABLE — can't defend!","Not important","Pro only"],1),q("One-footed = defenders?",["Can't read you","SHOW YOU onto weak side","Are confused","Don't care"],1),q("Feeling awkward?",["Give up","MEANS YOU'RE IMPROVING","Wrong","Stop"],1),q("In matches first?",["Front of goal","SAFE AREAS first","Never","Only pens"],1),q("Most pros?",["Never practice","SPECIFICALLY work on weak foot","Naturally two-footed","One foot only"],1),q("Opens?",["Nothing","NEW ANGLES","Old angles","No difference"],1),q("Target?",["Perfect","EVERYTHING strong foot does, slightly less well","Don't need one","Same level exactly"],1),q("Defenders vs one foot?",["Can't read","KNOW exactly what you'll do","Confused","Don't care"],1)]),

("jockeying","🛡️","Jockeying","Stay on Your Feet","#475569","The art of defending without diving in. Side-on, low, patient — force them where you want.",
["SIDE-ON stance, not square","Bent knees, low","Stay on FEET — don't dive in","Watch the BALL not body","Force onto WEAK FOOT","Arm's length distance","Shuffle — don't cross feet","Delay = defender's friend","Force toward touchline","Tackle only when ball is loose"],
[q("Jockeying stance?",["Square","SIDE-ON, low, patient","Tall","Backward"],1),q("Watch?",["Eyes","Hips","THE BALL!","Boots"],2),q("Stay on?",["Bum","FEET — don't dive in","Knees","Back"],1),q("Force them?",["Centre","WEAK FOOT / touchline","Forward","Toward your goal"],1),q("Distance?",["Touching","ARM'S LENGTH","10 metres","Very far"],1),q("Shuffle means?",["Cross feet","SLIDE without crossing","Jump","Stand still"],1),q("Delay is?",["Bad","DEFENDER'S FRIEND","Pointless","Boring"],1),q("Tackle when?",["Always","BALL LOOSE or heavy touch","Never","Only if told"],1),q("Low centre of gravity?",["Stand tall","BENT KNEES, ready","Lie down","Jump"],1),q("Diving in?",["Good","They go PAST you!","Normal","Required"],1)]),

("tackling","💪","Tackling","Timing & Technique","#b91c1c","Good tackle = win ball + stay on feet. Bad tackle = card or beaten.",
["BLOCK TACKLE: plant non-tackling foot, inside of other, drive through ball","Stay on feet whenever possible","Time it — wait for heavy touch","Body behind tackle, low and strong","NEVER tackle from behind (foul + card)","Slide tackle = LAST RESORT","Lean INTO the tackle","Win BALL first, not the man","After winning, KEEP POSSESSION","In air: time jump, strong, fair"],
[q("Block tackle: plant?",["Tackling foot","NON-TACKLING foot firm","Both","Neither"],1),q("When tackle?",["Anytime","BALL LOOSE/away from them","Never","Only in box"],1),q("From behind?",["Fine","FOUL + likely card!","Encouraged","Normal"],1),q("Slide tackle?",["First option","LAST RESORT","Every time","For fun"],1),q("After winning?",["Kick away","KEEP POSSESSION","Celebrate","Stop"],1),q("Body?",["Leaning away","LOW and behind — strong","Tall","Falling"],1),q("Win the?",["Man","BALL first","Both","Nothing"],1),q("Drive through?",["Stop at ball","Keep pushing THROUGH","Fall","Jump"],1),q("Timing waits for?",["Nothing","HEAVY TOUCH","Ref","Half-time"],1),q("Stay on?",["Ground","FEET whenever possible","Knees","Back"],1)]),

("offside","📐","Staying Onside","Runs & Positioning","#f59e0b","Offside costs goals. Understanding it wins them. The offside trap can be beaten.",
["Behind ball AND second-last defender when PLAYED","Stay in LINE with last defender","Check position before calling for ball","Time run: start BEHIND, burst through as ball played","Bend your run — curve behind then dart forward","NOT offside: own half, level, throw-in/GK/corner","Watch the passer — their shape = trigger to run","Offside TRAP: defenders step up together","Too early = offside, too late = ball's gone","Peel off the back — start onside, accelerate through"],
[q("Judged when ball?",["Received","PLAYED","Controlled","Shot"],1),q("Behind which?",["1 player","Ball AND second-last DEFENDER","3 players","GK only"],1),q("Stay onside?",["Stand still","LINE with last defender","Run offside","Own half always"],1),q("Time run?",["Guess","Start BEHIND, burst as ball played","Stand offside","Walk"],1),q("Offside trap?",["Run back","Defenders STEP UP together","All in goal","Goalkeeper only"],1),q("NOT offside in?",["Their half","OWN HALF","Box","Circle"],1),q("Passer shapes up =?",["Stop","TRIGGER to run!","Walk back","Stand still"],1),q("Bent run?",["Straight","CURVE behind then dart forward","Backward","Zigzag"],1),q("Level =?",["Offside","ONSIDE!","Foul","Penalty"],1),q("Too early?",["Perfect","OFFSIDE!","Great","On time"],1)]),

("def-shape","🧱","Defensive Shape","Marking & Covering","#334155","Defending is position, organisation and communication — not just tackling.",
["Goal-side: between attacker and YOUR goal","Track runners — they move, you move","Cover: drop behind if teammate presses","Compact: squeeze space between lines","Communicate: 'man on', 'turn', 'hold'","Zonal = defend SPACE","Man marking = follow one player","Don't ball-watch — check shoulders","Press as a UNIT not alone","Recovery run = SPRINT back"],
[q("Always stay?",["In front","GOAL-SIDE","Behind attacker","Level"],1),q("They move?",["Stay still","YOU MOVE","Let someone else","Go forward"],1),q("Cover means?",["Tackle","DROP BEHIND if teammate beaten","Attack","Head"],1),q("Compact?",["Spread out","SQUEEZE SPACE between lines","All in goal","All forward"],1),q("Ball-watch?",["Do it","DON'T — check shoulders for runners","Always","Only keeper"],1),q("Recovery run?",["Jog","SPRINT back!","Walk","Stand"],1),q("'Man on' means?",["Goal","DEFENDER BEHIND — careful!","Pass me","Offside"],1),q("Zonal defends?",["A person","An area of SPACE","Ball","Goal only"],1),q("Press as?",["Individual","UNIT — together","Pair","Solo"],1),q("Man marking?",["Guard area","FOLLOW ONE player everywhere","Guard ball","Stand still"],1)]),

("fifty-fifty","💥","Winning 50/50s","Desire & Technique","#ea580c","50/50 = who WANTS it more + who gets body right. Shows character.",
["DESIRE — want it MORE","Get there FIRST — anticipation","Low, strong, lean INTO challenge","Shoulder-to-shoulder = legal","Studs DOWN, arms tucked","Win it AND keep it","Don't pull out halfway — commit","First to ball sets tempo","In air: time jump, strong neck, elbows down","Managers LOVE 50/50 winners"],
[q("50/50 is about?",["Height","DESIRE — who wants it more!","Speed","Age"],1),q("Get there?",["Last","FIRST — anticipation!","Same time","Second"],1),q("Body?",["Soft","LOW, strong, lean IN","Backward","Upright"],1),q("Shoulder-to-shoulder?",["Foul","LEGAL and effective","Red card","Dangerous"],1),q("Pull out halfway?",["Smart","DANGEROUS — commit or don't go","Normal","Required"],1),q("After winning?",["Kick away","KEEP POSSESSION","Celebrate","Stop"],1),q("Elbows?",["Up high","DOWN — elbows up is a foul","Doesn't matter","Swing them"],1),q("50/50 winners show?",["Luck","CHARACTER and desire","Height","Nothing"],1),q("Studs?",["Up","DOWN — safe for everyone","Doesn't matter","Showing"],1),q("First to ball?",["Nothing","SETS THE TEMPO","Boring","Easy"],1)]),

("trans-da","🔄","Transition D→A","Counter-Attack","#059669","Win ball → go forward FAST. Opposition is out of position. The first 5 seconds are gold.",
["Win ball → FIRST THOUGHT: forward?","Quick forward pass beats whole teams","Look up IMMEDIATELY","Runners go INSTANTLY","Counter-attack = deadliest weapon","Direct: fewest passes to goal","Keep ball moving forward","If nothing on, keep possession","First 5 seconds most important","Midfielders become attackers — SPRINT"],
[q("After winning ball?",["Pass back","CAN WE GO FORWARD?","Slow down","Kick long"],1),q("Quick forward pass?",["Useless","Beats teams OUT OF POSITION","Too risky","Never"],1),q("Most important seconds?",["Last 5","FIRST 5","Middle","Doesn't matter"],1),q("Counter-attack?",["Boring","DEADLIEST weapon","Only bad teams","Not important"],1),q("Look?",["Down","UP IMMEDIATELY","Backward","At ref"],1),q("Runners?",["Wait","GO INSTANTLY","When they want","Only when told"],1),q("No forward pass?",["Kick out","KEEP POSSESSION and build","Panic","Shoot anywhere"],1),q("Direct play?",["Many passes","FEWEST passes to goal","Slow","Backward only"],1),q("Midfielders in transition?",["Defenders","ATTACKERS — sprint forward!","GK","Subs"],1),q("Best teams transition?",["Slowly","FAST before opposition recovers","Never","Only own half"],1)]),

("scanning","👀","Scanning","Check Before Receiving","#6d28d9","Top players scan 6-8 times in 10 seconds before receiving. Scanning = knowing what's on BEFORE the ball arrives.",
["Check LEFT shoulder, RIGHT shoulder BEFORE ball","Know where space, teammates, defenders are","Scan MORE when ball is far from you","Moment before receiving = most important scan","Without scanning: only backward/sideways options","Head on a swivel — constantly checking","Scanning lets you play FORWARD","Top mids scan 6-8 times per 10 seconds","Opens up through balls and switches","Practice scanning even in training drills"],
[q("Scanning means?",["Staring at ball","Check SHOULDERS before ball arrives","Watch crowd","Watch ref"],1),q("Why scan?",["Boredom","Know where SPACE/players are","Coach said","Rule"],1),q("Top players scan?",["Once","6-8 TIMES in 10 seconds!","Never","At half-time"],1),q("No scanning =?",["Forward","Only BACKWARD/sideways","No difference","More goals"],1),q("Most important scan?",["Half-time","BEFORE RECEIVING","After pass","Kick-off"],1),q("Scan more when ball?",["Close","FAR — more time to check","In goal","Out of play"],1),q("Head on swivel?",["Still","CONSTANTLY checking around","Spinning","Down"],1),q("Scanning enables?",["Backward play","FORWARD play — already know what's on","Slower play","Nothing"],1),q("Both shoulders?",["Left only","RIGHT only","LEFT and RIGHT","Neither"],2),q("Best mids?",["Don't scan","SCAN constantly — superpower","Scan once","Never look up"],1)]),

("movement","🏃‍♂️","Off-Ball Movement","Create Space","#0d9488","90% of football is without the ball. Movement off it is as important as what you do on it.",
["Runs BEHIND defence stretch them","DIAGONAL runs harder to track","Create space: move away, come back","Overlap: run OUTSIDE past winger","Underlap: run INSIDE winger","Pull defenders out to create space for others","Don't stand still — movement = confusion","Run hard when passer READY","Too early = offside, too late = gone","Point where you want the ball"],
[q("90% of football?",["On ball","WITHOUT the ball!","In goal","Still"],1),q("Diagonal runs?",["Easy to track","HARDER to track","Useless","Only strikers"],1),q("Create space?",["Stand still","MOVE AWAY then come back","Random runs","Stay put"],1),q("Overlap?",["Behind","OUTSIDE past winger","Backward","Still"],1),q("Run hard when?",["Anytime","PASSER READY to play","Never","Extra time"],1),q("Too early?",["Perfect","OFFSIDE!","Great","Late"],1),q("Movement creates?",["Nothing","CONFUSION for defenders","Tiredness","Problems"],1),q("Point where want ball?",["Useless","Helps passer KNOW where to play","Shows off","Wastes time"],1),q("Don't?",["Move","STAND STILL — always move!","Pass","Shoot"],1),q("Pull defenders?",["Push them","DRAG them out, space for teammates","Foul","Ignore"],1)]),

("one-v-one","🎭","1v1 Skills","Beat Your Defender","#be123c","You vs them. Tricks + decision-making + confidence = winning 1v1s.",
["Change of PACE = most effective (slow → BURST)","Step-over: swing foot over ball, go other way","Drop shoulder: dip one way, go other","Feint to shoot: shape then go around","Body movement > fancy tricks","Commit defender — shift their weight then go","Dribble AT them to force their decision","Space behind? Knock past and sprint","Protect ball: body between ball and defender","CONFIDENCE — believe you'll win"],
[q("Most effective?",["Step-over","CHANGE OF PACE — slow then burst","Rabona","Back-heel"],1),q("Step-over?",["Kick ball","Swing foot OVER, go other way","Step on it","Pass"],1),q("Drop shoulder?",["Fall over","Dip one way, go OTHER","Charge","Shout"],1),q("Commit defender?",["Foul","SHIFT THEIR WEIGHT then go other way","Push","Shout"],1),q("1v1 about?",["Luck","CONFIDENCE","Height","Speed only"],1),q("Body movement vs tricks?",["Tricks better","BODY FEINTS more effective","Same","Neither"],1),q("Space behind?",["Ignore","KNOCK PAST and use pace","Pass back","Shoot"],1),q("Dribble AT them?",["Scare them","FORCE their decision","Get fouled","Waste time"],1),q("Protect ball?",["Kick away","BODY between ball and defender","Sit on it","Pass back"],1),q("Feint to shoot?",["Actually shoot","MAKES DEFENDER commit then go around","Miss","Fall over"],1)]),

("finishing","🥅","Finishing","Calm in Front of Goal","#dc2626","The difference between good players and goalscorers: COMPOSURE in front of goal.",
["PICK YOUR SPOT before shooting","Side foot = most reliable finish","Across keeper = hardest save","Low corners = keepers hate","1v1: round keeper or slide to corner","If in doubt HIT THE TARGET","Extra touch if needed — composure beats rushing","Eyes on ball at contact","One deep breath calms nerves","Practice finishing TIRED"],
[q("Before shooting?",["Close eyes","PICK YOUR SPOT","Blast random","Pass back"],1),q("Side foot?",["Powerful","MOST RELIABLE for placement","Weak","Only passes"],1),q("Across keeper?",["At them","FAR CORNER — hardest to save","Over bar","Into hands"],1),q("1v1 with keeper?",["Blast","ROUND THEM or side to corner","Pass back","Head"],1),q("In doubt?",["Don't shoot","HIT THE TARGET!","Pass back","Wait"],1),q("Composure?",["Panic","CALM, pick spot, take time","Rush","Blast it"],1),q("Eyes at contact?",["On goal","ON THE BALL","On keeper","Closed"],1),q("Calm nerves?",["More panic","ONE DEEP BREATH","Running away","Shouting"],1),q("Practice when?",["Fresh","TIRED — when matches decided!","Never","Warm-up"],1),q("Low corners?",["Easy for keepers","HARDEST to save!","Pointless","Only pens"],1)]),

("combo-play","🤝","Combination Play","Wall Pass & Third Man","#6d28d9","Football is a team game. 2-3 players combining unlocks any defence.",
["WALL PASS: pass, run past defender, receive return","Third man: A→B, C runs, B plays to C","Timing: run when ball played","Quick passing beats pressing","Rotation: swap positions, confuse defence","First time when possible","Create ANGLES off the ball","Communicate: shout, point to space","Trust teammates — expect the return","Wall passes best in final third"],
[q("Wall pass?",["Long ball","Pass, run past, RECEIVE RETURN","Heading","Throw"],1),q("Third man?",["Third player","A→B, C runs, B PLAYS TO C","Three passes","Three goals"],1),q("Quick passing beats?",["Nothing","PRESSING","Slow play","Long balls"],1),q("First time?",["Never","When POSSIBLE for speed","Always","Own half"],1),q("Angles?",["Stand in line","Move OFF THE LINE of ball","Still","Backward"],1),q("After wall pass?",["Stand still","RUN PAST for return!","Walk","Pass back"],1),q("Rotation?",["Circles","SWAP POSITIONS to confuse","Stay put","Only GK"],1),q("Wall passes best?",["Own half","FINAL THIRD — near goal","Halfway","In goal"],1),q("Trust means?",["Don't pass","Pass and EXPECT RETURN","Only self","Run with it"],1),q("Communicate?",["Silent","SHOUT, point to space","Wave","Stand still"],1)]),

("crossing","⚽","Crossing","Delivery to the Box","#0891b2","A good cross = chances. It's a PASS to a specific target, not just kicking it in.",
["Aim BETWEEN keeper and defenders","Early cross: before byline, catches defence out","Byline: get to goal line, pull back","Whipped: inside foot, curl AWAY from keeper","Low driven: hard, flat — hardest to defend","LOOK UP before crossing","A cross is a PASS — pick your target","Vary: near post, far post, low, high","Cross away from keeper","Pull-back = most dangerous cross"],
[q("Aim cross?",["At keeper","BETWEEN keeper and defenders","Behind goal","At CB"],1),q("Early cross?",["Late","BEFORE byline — catches defence out","After whistle","Half-time"],1),q("Cross is?",["Shot","A PASS — pick target!","Clearance","Goal kick"],1),q("Whipped curls?",["Toward keeper","AWAY from keeper","Straight","Backward"],1),q("Low driven?",["Easy defend","HARDEST to defend","Pointless","Only corners"],1),q("Before crossing?",["Close eyes","LOOK UP — see who's where","Cross random","Pass back"],1),q("Vary?",["Same always","MIX IT UP","Never cross","Only near"],1),q("Pull-back?",["Boring","MOST DANGEROUS cross — along ground from byline","Easy to defend","Useless"],1),q("Cross away from keeper?",["They catch it","ATTACKERS can run onto it","Goes out","Heading"],1),q("Byline cross?",["From halfway","Get to GOAL LINE, pull back","Corner","Free kick"],1)]),

("set-pieces","🎯","Set Pieces","Corners, FKs & Throw-ins","#1d4ed8","30% of goals come from set pieces. They're rehearsed and practised.",
["Corners: in-swing or out-swing","Near post flick-ons, far post headers","FK shooting: over wall = dip, around = curl","FK crossing: more time to pick target","Throw-ins: both feet, both hands, behind head","Long throws = dangerous weapon","30% of goals from set pieces","Practice routines until automatic","Quick FKs catch teams out","First to ball wins set pieces"],
[q("Goals from set pieces?",["5%","30%!","50%","1%"],1),q("In-swing corner goes?",["Away from goal","TOWARD goal","Straight","Backward"],1),q("Throw-in feet?",["One","BOTH on/behind line","In air","Doesn't matter"],1),q("Quick FK?",["Never","CATCHES TEAMS OUT","Against rules","Only in ET"],1),q("FK over wall?",["Low","DIP IT — up and over then down","Around","Under"],1),q("Long throws?",["Pointless","DANGEROUS weapon","Against rules","Only GK"],1),q("First to ball at set piece?",["Doesn't matter","WINS the set piece!","Let it bounce","Duck"],1),q("Practice routines?",["Once","UNTIL AUTOMATIC","Never","Only matchday"],1),q("Both hands throw-in?",["Optional","REQUIRED — behind head","One hand OK","Doesn't matter"],1),q("Out-swing corner?",["Toward goal","AWAY from goal — attackers run onto it","Straight","Backward"],1)]),

("trans-ad","🔄","Transition A→D","Lose Ball, React FAST","#dc2626","Lost the ball? The next 6 seconds decide everything. Press immediately or get back in shape.",
["Lose ball → IMMEDIATE reaction","Counter-press: swarm the ball within 6 seconds","Nearest players press, others get back","Don't stand and watch — REACT","6-second rule: press or recover shape","If can't win back, delay their counter","Sprint back — recovery runs win games","Communicate: 'press!', 'drop!', 'recover!'","Attitude: WE lost it, not one person's fault","Transition = the moment matches are won and lost"],
[q("Lose ball, first reaction?",["Stand still","IMMEDIATE press or recovery!","Walk back","Blame teammate"],1),q("Counter-press within?",["30 seconds","6 SECONDS","1 minute","Never"],1),q("If can't win back?",["Give up","DELAY their counter","Stand","Watch"],1),q("Recovery runs?",["Jog","SPRINT back!","Walk","Stand"],1),q("6-second rule?",["Press or RECOVER SHAPE","Ignore","Not real","Only pros"],1),q("Communicate?",["Silent","PRESS! DROP! RECOVER!","Blame","Nothing"],1),q("Transition =?",["Boring","MOMENT MATCHES WON AND LOST","Not important","Only in ET"],1),q("Nearest players?",["Watch","PRESS the ball","Run away","Stand"],1),q("Attitude?",["Blame someone","WE lost it — team effort","Not my fault","Give up"],1),q("Don't?",["React","STAND AND WATCH","Press","Sprint"],1)]),

("comms","📢","Communication","Talk on the Pitch","#1d4ed8","The best teams TALK. Communication = free information for your teammates.",
["'MAN ON' = defender behind you","'TURN' = space to turn, go forward","'HOLD' = keep the ball, don't turn yet","'DROP' = pass back to me","'TIME' = you have time on the ball","'SWITCH' = change play to other side","Call for the ball — don't just wave","Organise at set pieces — call who marks who","GK and CB = main communicators","Talk BEFORE, during, and after the ball"],
[q("'Man on' means?",["Nice goal","DEFENDER BEHIND — careful!","Pass me","Offside"],1),q("'Turn' means?",["Don't turn","SPACE TO TURN — go forward!","Pass back","Shoot"],1),q("'Time' means?",["Hurry","YOU HAVE TIME on ball — don't rush","Half-time","Full-time"],1),q("Call for ball by?",["Waving","SHOUTING clearly","Telepathy","Standing still"],1),q("Main communicators?",["Wingers","GK and CB — they see the whole pitch","Strikers","Subs"],1),q("'Hold' means?",["Let go","KEEP BALL, don't turn yet","Shoot","Run"],1),q("'Switch' means?",["Stay","CHANGE PLAY to other side","Swap players","Sub"],1),q("'Drop' means?",["Fall over","PASS BACK to me","Shoot","Run forward"],1),q("Talk when?",["Only when told","BEFORE, during, and AFTER ball","Never","At half-time"],1),q("Communication is?",["Unnecessary","FREE INFORMATION for teammates","Annoying","Only for pros"],1)]),

("build-up","🧱","Playing Out","Build From the Back","#059669","The best teams play out from the back with composure. Brave on the ball, find the free player.",
["GK starts: short to CB or FB","CBs split wide, CDM drops between them = triangle","Full-backs push high = width","If pressed, GK can go long — no shame","Composure: don't panic with ball at back","Find the FREE PLAYER — they exist","One-touch if pressed, two-touch if time","CDM = most important position in build-up","Draw their press then play through it","Switching play = exploits spaces"],
[q("GK starts by?",["Hoofing it","SHORT to CB or FB","Throwing to striker","Kicking out"],1),q("CBs do what?",["Stay narrow","SPLIT WIDE to create space","Go forward","Sit"],1),q("CDM drops?",["Forward","BETWEEN CBS = triangle","To bench","Wide"],1),q("If pressed hard?",["Panic","GK CAN GO LONG — no shame","Give away","Dribble"],1),q("Composure means?",["Rush","DON'T PANIC with ball at back","Kick long always","Hoof it"],1),q("Free player?",["Doesn't exist","ALWAYS EXISTS — find them!","Only in your half","Only striker"],1),q("If pressed: how many touches?",["10","ONE-TOUCH if pressed","Always two","Doesn't matter"],1),q("Most important build-up position?",["Striker","CDM","Winger","GK"],1),q("Draw their press then?",["Panic","PLAY THROUGH IT","Kick out","Foul"],1),q("Switching play?",["Pointless","EXPLOITS SPACES on far side","Too risky","Only for pros"],1)]),

("pressing","💨","Pressing","Win it High","#dc2626","Pressing = closing down the ball as a TEAM to win it back high up the pitch. The closer to their goal you win it, the better the chance.",
["Press as a UNIT — not alone","Trigger: bad touch, back-pass, player facing own goal","Cut passing lanes while pressing ball","Force them toward touchline","HIGH press = win it near THEIR goal = big chance","Sprint to press, then drop if not working","Press from the FRONT — strikers press first","Intensity: all-out for 5-6 seconds","If beaten, recover quickly","Communication: 'GO!', 'PRESS!', 'DROP!'"],
[q("Press as?",["Individual","A UNIT — together!","Pair","Solo"],1),q("Press trigger?",["Any time","BAD TOUCH, back-pass, facing own goal","Never","Only when told"],1),q("High press wins ball near?",["Your goal","THEIR goal = big chance!","Halfway","Doesn't matter"],1),q("Pressing is?",["One player closing","WHOLE TEAM closing down together","Only strikers","Only defenders"],1),q("Cut passing?",["Nothing","LANES while pressing ball","Players","Grass"],1),q("Sprint then?",["Stand","DROP if not working","Keep sprinting forever","Walk"],1),q("Who presses first?",["GK","Defenders","STRIKERS from the front","Nobody"],1),q("Intensity lasts?",["1 second","5-6 SECONDS all-out","All game","1 minute"],1),q("If beaten?",["Give up","RECOVER QUICKLY","Stand","Complain"],1),q("Force them?",["Centre","TOWARD TOUCHLINE","Forward","Into space"],1)]),

("penalties","🎯","Penalties","Take & Save Them","#7c3aed","Penalties are 80% mental. DECIDE where to put it and commit. Keepers: watch the hips, react don't guess.",
["Decide spot BEFORE walking up","Side foot to corner = most reliable","Confidence = walk up knowing you'll score","Strike through, don't stab","Placement > power","Keeper: stay big, central","Watch HIPS for direction","React don't guess","Consistent run-up","Practice under pressure"],
[q("When decide spot?",["Mid run-up","BEFORE walking up — commit!","After striking","During sleep"],1),q("Best technique?",["Blast","SIDE FOOT to corner","Chip always","Back-heel"],1),q("Placement vs power?",["Power wins","PLACEMENT wins!","Same","Doesn't matter"],1),q("Keeper watches?",["Ball only","HIPS — they point where ball goes","Eyes","Crowd"],1),q("Keeper dives?",["Before strike","Slightly AFTER — react don't guess","During run-up","Random"],1),q("Change your mind?",["All the time","DON'T — commit to your decision","Every penalty","During run-up"],1),q("Walk up with?",["Fear","CONFIDENCE — you'll score","Doubt","Nerves"],1),q("Strike through means?",["Stop at ball","Keep foot going THROUGH the ball","Stab","Toe poke"],1),q("Stay big means keeper?",["Small","SPREAD and take up space","Dive early","Jump"],1),q("Practice pens?",["Once","Under PRESSURE regularly","Never","Only matchday"],1)]),

("game-iq","🧠","Game Intelligence","Read the Game","#6d28d9","The best don't just play — they THINK. Reading the game = being in the right place at the right time.",
["Position yourself where ball is going, not where it IS","Anticipate — read body language of opponents","Know when to press vs drop deep","Space awareness: find pockets between lines","Game management: protect a lead, chase a deficit differently","Vary your play — predictable = easy to defend","Use the whole pitch — don't bunch up","When tired: simpler decisions, keep the ball","Recognise patterns: their GK always goes short? Press it","Think 2 passes ahead"],
[q("Position where?",["Ball is","Where ball is GOING","Goal","Bench"],1),q("Anticipate means?",["Guess","READ body language, predict next move","Wait","Do nothing"],1),q("When to press vs drop?",["Always press","Depends on GAME SITUATION","Always drop","Never press"],1),q("Think how far ahead?",["1 pass","2 PASSES ahead","Not at all","10 passes"],1),q("Predictable =?",["Good","EASY to defend","Unbeatable","Fast"],1),q("When tired?",["Complex play","SIMPLER decisions, keep ball","Give up","Run more"],1),q("Use?",["Small area","WHOLE PITCH","Own half","Only centre"],1),q("Recognise patterns?",["Ignore them","EXPLOIT THEM — e.g. press short GK","Don't look","Not important"],1),q("Space between lines?",["Avoid","FIND POCKETS there — dangerous!","Doesn't exist","Only for strikers"],1),q("Game management?",["Same approach always","ADAPT — protect lead or chase differently","Ignore score","Not real"],1)]),

("mental","💪","Mental Toughness","Confidence & Resilience","#475569","Mistakes happen. Bad games happen. Mental toughness = bouncing back and keeping going.",
["Mistakes are NORMAL — every player makes them","Next ball mentality: forget the last mistake, focus on next action","Confidence comes from PREPARATION","Positive self-talk: 'I've got this' not 'I hope I don't mess up'","Body language: walk tall even when struggling","Pressure = privilege — means the moment matters","Visualise success before the game","Support teammates — lift them, don't criticise","Breathe: 4 in, 4 out before big moments","You're allowed to be nervous — turn it into energy"],
[q("Mistakes?",["Unacceptable","NORMAL — every player makes them","Career ending","Rare"],1),q("After a mistake?",["Dwell on it","NEXT BALL — focus on next action","Give up","Blame others"],1),q("Confidence from?",["Nothing","PREPARATION and practice","Born with it","Luck"],1),q("Self-talk?",["'I'm rubbish'","'I'VE GOT THIS'","'I hope not'","Silence"],1),q("Body language?",["Slouch","WALK TALL even when struggling","Hide","Head down"],1),q("Pressure?",["Bad","PRIVILEGE — moment matters","Run away","Give up"],1),q("Before big moments?",["Panic","BREATHE: 4 in, 4 out","Hyperventilate","Don't prepare"],1),q("Nervous?",["Bad sign","NORMAL — turn into energy!","Give up","You're weak"],1),q("Teammates struggling?",["Criticise","LIFT THEM UP","Ignore","Blame"],1),q("Visualise?",["Failure","SUCCESS before the game","Nothing","Sleep"],1)]),

("fitness","🏋️","Fitness","Stamina & Speed","#16a34a","The fitter you are, the better your decisions in the 80th minute. Fitness = focus.",
["Football is interval: sprint → jog → sprint","Build base fitness: running 20-30 mins steady","Sprint training: short bursts, recover, repeat","Core strength = balance, shooting power, winning challenges","Agility: ladder drills, cone work, quick feet","Recovery: stretch AFTER training, sleep 8-9 hours","Hydrate before, during, after","Pre-season = build fitness BEFORE season","80th minute: fit players make better decisions","Fittest players are the last ones running"],
[q("Football fitness is?",["Just running","INTERVAL — sprint, jog, sprint","Slow jog only","Weights only"],1),q("Base fitness?",["Sprints only","STEADY RUNNING 20-30 mins","Sit-ups","Walking"],1),q("Core strength helps?",["Nothing","BALANCE, power, challenges","Only abs","Looks"],1),q("Recovery?",["Skip","STRETCH, sleep 8-9 hours","Keep training","Nothing"],1),q("Hydrate?",["Only after","BEFORE, during, after","Never","Only water"],1),q("80th minute: fit players?",["Same","BETTER DECISIONS","Don't exist","Walk"],1),q("Agility?",["Slow running","LADDER drills, cones, quick feet","Just sprints","Nothing"],1),q("Pre-season?",["Rest","BUILD FITNESS before season","Skip","Easy"],1),q("Sprint training?",["Long runs","SHORT BURSTS, recover, repeat","Walking","Jogging only"],1),q("Fittest players?",["Stop first","LAST ONES RUNNING","Don't matter","Average"],1)]),

("weather","🌧️","Playing in Weather","Rain, Wind & Cold","#64748b","Weather changes how you play. Smart players adapt. Others complain.",
["WET: ball skids faster — pass firmer, control softer","WET: shoot low — ball skids past keeper","WIND with you: play ball on ground, let wind carry you forward","WIND against: keep passes low, don't play high balls","COLD: warm up properly — injury risk higher","WET: shorter studs can slip — check your boots","WET: stay on feet even more — sliding = out of position","WIND: corners and FKs need adjusting","All weather: first touch even MORE important","Mental: don't let weather affect your attitude"],
[q("Wet pitch: ball?",["Slows","SKIDS FASTER","No difference","Stops"],1),q("Wet: shoot?",["High","LOW — skids past keeper","Normal","Don't shoot"],1),q("Wind with you?",["High balls","BALL ON GROUND, wind carries forward","Against wind tactics","Doesn't matter"],1),q("Wind against?",["High balls","Keep PASSES LOW","Same as normal","Don't play"],1),q("Cold?",["Skip warm-up","WARM UP PROPERLY — injury risk","Doesn't matter","Stay inside"],1),q("Wet: first touch?",["Less important","EVEN MORE IMPORTANT","Same","Don't control"],1),q("Wet: stay on?",["Ground","FEET — sliding = out of position","Knees","Back"],1),q("Mental approach?",["Complain","DON'T LET WEATHER affect attitude","Give up","Hide"],1),q("Wet boots?",["Any boots","CHECK STUDS — right length","Doesn't matter","No boots"],1),q("Wind affects?",["Nothing","CORNERS, FKs, high passes — adjust!","Only shooting","Only GK"],1)]),

("pre-match","📋","Pre-Match Routine","Body & Mind Ready","#7c3aed","What you do in the 24 hours before a match matters more than you think. Sleep, food, warm-up, mindset.",
["Early bed, 8-9 hours","Breakfast 2-3 hours before","Hydrate from morning","No heavy food within 2 hours","Warm up properly","Visualise success","Listen to team talk","Sharp final prep","Deep breaths","Walk out with confidence"],
[q("Night before?",["Late night","EARLY BED, 8-9 hours sleep","Doesn't matter","Stay up"],1),q("Breakfast?",["Skip it","PORRIDGE/toast/banana 2-3 hrs before","Big fry-up","Sweets"],1),q("Hydrate?",["Only at half-time","FROM THE MORNING","Not important","After game only"],1),q("Heavy food within 2 hours?",["Fine","NO — too close to game","Required","Doesn't matter"],1),q("Warm-up includes?",["Static stretches only","JOG, dynamic stretches, ball work","Sitting down","Nothing"],1),q("Visualise?",["Failure","SUCCESS — see yourself playing well","Nothing","Sleep"],1),q("Before kick-off?",["Panic","DEEP BREATHS: 4 in, 4 out","Hyperventilate","Chat"],1),q("Walk out?",["Slouching","With PURPOSE and confidence","Nervous","Slowly"],1),q("Final prep?",["Sit down","SHARP passes, few shots","Heavy running","Nothing"],1),q("Team talk?",["Ignore","LISTEN, focus, take in the plan","Chat","Zone out"],1)]),

("legends","⭐","Learn From the Best","What Made Them Great","#f59e0b","Every great player got there through work, not just talent. Messi practised dribbling for hours. Ronaldo was first in, last out. De Bruyne scans constantly. They ALL worked incredibly hard.",
["Messi: low gravity, change of pace, practice","Ronaldo: work ethic, both feet, fitness","De Bruyne: scanning, vision, both feet","Van Dijk: reads game, composure, doesn't dive in","Modric: proves size doesn't matter","Mbappe: pace, direct, finishing","Talent isn't enough","Work ethic = everything","Learn from watching them play","Apply their principles to YOUR game"],
[q("Messi practised what for hours?",["Headers","DRIBBLING","Goalkeeping","Defending"],1),q("Ronaldo is known for?",["Laziness","INCREDIBLE WORK ETHIC","Only left foot","Never heading"],1),q("De Bruyne's superpower?",["Speed","SCANNING — sees passes nobody else sees","Height","Tackling"],1),q("Van Dijk rarely?",["Heads","DIVES IN — reads the game instead","Passes","Communicates"],1),q("Modric proves?",["Big = better","SIZE DOESN'T MATTER","Speed is everything","Only height matters"],1),q("ALL great players?",["Born great","WORKED INCREDIBLY HARD","Were lucky","Had no talent"],1),q("Talent alone?",["Is enough","ISN'T ENOUGH — need work ethic","Guarantees success","No work needed"],1),q("Mbappe excels in?",["Slow build-up","EXPLOSIVE TRANSITIONS and pace","Defending","Goalkeeping"],1),q("Learn from them by?",["Doing nothing","WATCHING and applying to YOUR game","Just watching","Copying exactly"],1),q("Gerrard known for?",["Quiet","LEADERSHIP and big goals","Only defending","Being small"],1)]),
]

for id,icon,title,sub,color,intro,steps,quiz in bulk:
    CH.append(ch(id,icon,title,sub,color,intro,[],steps,quiz))

# Save
with open('/home/claude/football-app/data.js','w') as f:
    f.write('const CH='+json.dumps(CH,ensure_ascii=False)+';')
print(f"✅ {len(CH)} chapters built")
print(f"✅ {sum(len(c['quiz']) for c in CH)} quiz questions")
print(f"✅ Chapters: {[c['title'] for c in CH]}")
